LEGOINNOVATIVE/Pages/Sites/CustomerProfile.cshtml.cs
using LEGOINNOVATIVE.MockData;
using LEGOINNOVATIVE.Model;
using LEGOINNOVATIVE.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LEGOINNOVATIVE.Pages.Sites
{
    public class CustomerProfileModel : PageModel
    {
        private ILoginService _loginService;
        private IOrderService _orderService;
        public Profiles Profiles { get; set; }
        public List<Order> Orders { get; set; }

        public void OnGet()
        {
            Profiles = _loginService.Profiles;
            Orders = _orderService.GetOrders();
        }
        public CustomerProfileModel(ILoginService loginService, IOrderService orderService)
        {
            _loginService = loginService;
            _orderService = orderService;
        }
    }
}

LEGOINNOVATIVE/Pages/Sites/Innovative.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LEGOINNOVATIVE.Pages.Sites
{
    public class InnovativeModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

LEGOINNOVATIVE/Pages/Sites/MasterProfile.cshtml.cs
using LEGOINNOVATIVE.Model;
using LEGOINNOVATIVE.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LEGOINNOVATIVE.Pages.Sites
{
    public class MasterProfileModel : PageModel
    {
        private ILoginService _loginService;
        private IOrderService _orderService;
        public Profiles Profiles { get; set; }
        public List<Order> Orders { get; set; }

        public void OnGet()
        {
            Profiles = _loginService.Profiles;
            Orders = _orderService.GetOrders();
        }

        public IActionResult OnPostRemove(int id)
        {
            _orderService.DeleteOrder(id);
            return RedirectToPage("/Sites/MasterProfile");
        }

        public MasterProfileModel(ILoginService loginService, IOrderService orderService)
        {
            _loginService = loginService;
            _orderService = orderService;
        }
    }
}

LEGOINNOVATIVE/Pages/Sites/Overview.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LEGOINNOVATIVE.Pages.Sites
{
    public class OverviewModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

LEGOINNOVATIVE/Pages/Sites/CustomerProfile.cshtml
@page
@model LEGOINNOVATIVE.Pages.Sites.CustomerProfileModel
@{
}
<body class="CustomerProfileBackground">
    <h1 class="ProfileHeader">Profile</h1>
        <div class="Textboxes">
            <p class="ProfileTextbox">Name : @Model.Profiles.Name</p>
            <p class="ProfileTextbox">Adress : @Model.Profiles.Adress</p>
            <p class="ProfileTextbox">Email : @Model.Profiles.Email</p>
            <p class="ProfileTextbox">Phone : @Model.Profiles.Phone</p>
        </div>
    <div class="YourOrders">
        <h2 class="RequestHeader">Your orders</h2>
        <table class="table table-hover">
            <thead >
                <tr class ="TableRow">
                    <th>ID</th>
                    <th>Title</th>
                    <th>Plan</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="TableBodyCompleted">
                @foreach (var item in Model.Orders){
                    if (Model.Profiles.Email == item.Email){
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Title</td>
                            <td>@item.Plan</td>
                            <td>@item.Description</td>
                            @if (item.Accepted == false && item.Completed == false){
                                <td>Pending</td>
                                }else if (item.Accepted == true && item.Completed == false){
                                    <td>In progress</td>
                                }
                                else if (item.Accepted == true && item.Completed == true){
                                    <td>Completed</td>
                                }
                            <td><a class="arrowButton" asp-page="/Orders/OrderDetails" asp-route-id="@item.Id">&#62;</a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</body>

LEGOINNOVATIVE/Pages/Sites/Innovative.cshtml
@page
@model LEGOINNOVATIVE.Pages.Sites.InnovativeModel
@{
}

<div class="InnovativeInfoBackground1">
    <p class="InnovativeInfoHeader">LEGO INNOVATION</p>
    <p class="InnovativeInfoSlogan">Design by you</p>
</div>

<div class="InnovativeInfoBackground2">
    <p class="Section1Header">DESIGN</p>
    <p class="Section1Description">Design and create your own LEGO ideas. <br /> 
    Tell us your LEGO Idea is and we will make it come true.    
    </p>
    <img class="Section1Pic" src="~/media/pictures/Design-pic.png" />
</div>

<div class="InnovativeInfoBackground3">
    <p class="Section2Header">COMMUNICATION</p>
    <p class="Section2Description">Our Masterbuilders is always ready to help you with your Idea.<br />
        Together you will succed in creating your personal Idea through communication.<br />
    </p>
    <img class="Section2Pic" src="~/media/pictures/Communication-logo.png"/>
</div>

<div class="InnovativeInfoBackground4">
    <p class="Section3Header">PACKAGING</p>
    <p class="Section3Description">Recieve an exclusive package, special made for LEGO INNOVATIVE <br />
        Our packages is 100% made of recycled materials, and is completely CO2 neutral. <br />
        Choose the package for your needs! <br />
        psst... Some plans will give you the option to write a personal message.
    </p>
    <img class="Section3Pic" src="~/media/pictures/Box - signature vertical.png"/>
</div>

<div class="InnovativeInfoBackground5">
    <p class="Section4Header">BUILD</p>
    <p class="Section4Description">When your order is complete, we'll send you <br />
        your package with your design. <br /> <br />
        Our skillful Masterbuilders will make sure to <br /> send the parts needed and a manual on how to build your idea!<br /><br />
        Get building!
    </p>
    <img class="Section4Pic" src="~/media/pictures/Build-Logo.png"/>
</div>
<div class="InnovativeInfoBackground6">
    <p class="Section5Header">PICK YOUR IDEA</p>
    <div class="PlanDiv">
    <img src="~/media/pictures/StarterPlan.png"/>
    <img src="~/media/pictures/HobbyPlan.png"/>
    <img src="~/media/pictures/EnthusiastPlan.png"/>
    <img src="~/media/pictures/MasterPlan.png"/>
    </div>
    <a class="PlansLink" asp-page="/Sites/Overview">SEE PLANS</a>
</div>

LEGOINNOVATIVE/Pages/Sites/MasterProfile.cshtml
@page
@model LEGOINNOVATIVE.Pages.Sites.MasterProfileModel
@{
}

<body class="MasterBody">
    <h1 class="MasterHeader">MASTERBUILDER</h1>

    <div class="MasterTable">
        <h2 class="RequestHeader">Requests</h2>
        <table class="table table-hover">
            <thead>
                <tr class="TableRow">
                    <th>ID</th>
                    <th>Title</th>
                    <th>Plan</th>
                    <th>Description</th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="TableBody">
                @foreach (var item in Model.Orders)
                {
                    if (item.Accepted == false && item.Completed == false) 
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Title</td>
                            <td>@item.Plan</td>
                            <td>@item.Description</td>
                            <td><a class="arrowButton" asp-page="/Orders/OrderRequests" asp-route-id="@item.Id">&#62;</a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    <div class="MasterTable">
        <h2 class="ActiveHeader">Active</h2>
        <table class="table table-hover">
            <thead>
                <tr class="TableRow">
                    <th>ID</th>
                    <th>Title</th>
                    <th>Plan</th>
                    <th>Description</th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="TableBodyActive">
                @foreach (var item in Model.Orders)
                {
                    if (item.Accepted == true && item.Completed == false) 
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Title</td>
                            <td>@item.Plan</td>
                            <td>@item.Description</td>
                            <td><a class="arrowButton" asp-page="/Orders/OrderActive" asp-route-id="@item.Id">&#62;</a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    <div class="MasterTable">
        <h2 class="CompletedHeader">Completed</h2>
        <table class="table table-hover">
            <thead>
                <tr class="TableRow">
                    <th>ID</th>
                    <th>Title</th>
                    <th>Plan</th>
                    <th>Description</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="TableBodyCompleted">
                @foreach (var item in Model.Orders)
                {
                    if (item.Accepted == true && item.Completed == true) 
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Title</td>
                            <td>@item.Plan</td>
                            <td>@item.Description</td>
                            <td><a class="arrowButton" asp-page="/Orders/OrderActive" asp-route-id="@item.Id">&#62;</a></td>
                            <form method="post">
                            <td><input value="Remove" type="submit" class="removeButton" asp-page-handler="Remove" asp-route-id="@item.Id"/> </td>
                            </form>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</body>

LEGOINNOVATIVE/Pages/Sites/Overview.cshtml
@page
@model LEGOINNOVATIVE.Pages.Sites.OverviewModel
@{
}

<body>
    <div class="overview1-background">
        <div class="overviewParrent">
            <div>
                <a asp-page="/Orders/MakeOrder"><img class="overviewPic" src="~/media/pictures/StarterPlan.png" /></a>
            </div>
            <div class="overviewDescription">
                <h1 class="overviewHeader">STARTER</h1>
                <p class="overviewText">The starter package gives you the opportunity for a small idea, but nevertheless a great one! <br />
                You will recieve 1 minifigure, and a maximum of 500 bricks to use. <br />
                This package is perfect for casual LEGO play or as a gift. 
                </p>
            </div>
        </div> 
    </div>
    <div class="overview2-background">
        <div class="overviewParrent1080">
            <div>
                <a asp-page="/Orders/MakeOrder"><img class="overviewPic" src="~/media/pictures/HobbyPlan.png" /></a>
            </div>
            <div class="overviewDescription">
                <h1 class="overviewHeader">HOBBY</h1>
                <p class="overviewText">
                    Our most popular plan yet - HOBBY. The perfect plan for a medium build. <br />
                    The plan contains 3 minifigures, and a maximum of 1000 bricks to use. <br />
                    This package is optimized for a playfull and a creative building experience.
                </p>
            </div>
        </div>
    </div>
    <div class="overview3-background">
        <div class="overviewParrent1080">
            <div>
                <a asp-page="/Orders/MakeOrder"><img class="overviewPic" src="~/media/pictures/EnthusiastPlan.png" /></a>
            </div>
            <div class="overviewDescription">
                <h1 class="overviewHeader">ENTHUSIAST</h1>
                <p class="overviewText">
                    The Enthusiast plan is for our enthusiastic builders. <br />
                    The plan contains 5 minifigures, and a maximum of 2000 bricks to use. <br />
                    This package also gives the oppertunity for a personal message on the packaging.<br />
                    Select the Enthusiast plan for a more difficult building experince.
                </p>
            </div>
        </div>
    </div>
    <div class="overview4-background">
        <div class="overviewParrent1080">
            <div>
                <a asp-page="/Orders/MakeOrder"><img class="overviewPic" src="~/media/pictures/MasterPlan.png" /></a>
            </div>
            <div class="overviewDescription">
                <h1 class="overviewHeader">MASTER</h1>
                <p class="overviewText">
                    Our biggest package with 3500 bricks and a personal Brick Me Figure <br />
                    The plan contains up to five minifigures and a personal message <br />
                    The Master plan is perfert for a long-time build and for our most experinced LEGO builders.
                </p>
            </div>
        </div>
    </div>
</body>