LEGOINNOVATIVE/Pages/Orders/MakeOrder.cshtml.cs
using LEGOINNOVATIVE.MockData;
using LEGOINNOVATIVE.Model;
using LEGOINNOVATIVE.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace LEGOINNOVATIVE.Pages.Orders
{
    public class MakeOrderModel : PageModel
    {

        private IOrderService _orderService;
        private ILoginService _loginService;

        private MockPlans mockPlans = new MockPlans();

        public Profiles ProfileLoggedIn { get; set; }

        [BindProperty, Required(ErrorMessage ="Title is required")]
        public string Title { get; set; }

        [BindProperty, Required(ErrorMessage = "Description is required")]
        public string Description { get; set; }
        [BindProperty]
        public string PersonalMessage { get; set; }

        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public bool Publish { get; set; }

        public List<string> Plans { get; set; }
        [BindProperty]
        public string ChosenPlan { get; set; }
        public void OnGet()
        {
            Plans = new List<string>();

            foreach (var pl in mockPlans.GetMockPlans())
            {
                Plans.Add(pl.Type);
            }
        }

        public int MakeId()
        {
                Id = _orderService.GetOrders().Count + 1;
                return Id;
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            ProfileLoggedIn = _loginService.FindProfile(_loginService.Profiles.Email);
            Order newOrder = new Order(Title, Description, PersonalMessage, MakeId(), Publish, ChosenPlan, ProfileLoggedIn.Email);

            MockOrders mockOrders = new MockOrders();
            mockOrders.Add(newOrder);
            _orderService.Add(newOrder);
            return RedirectToPage("/Sites/CustomerProfile");
        }

        public MakeOrderModel(IOrderService service, ILoginService loginService)
        {
            _orderService = service;
            _loginService = loginService;
        }


    }
}

LEGOINNOVATIVE/Pages/Orders/OrderActive.cshtml.cs
using LEGOINNOVATIVE.Model;
using LEGOINNOVATIVE.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Numerics;
using System.Xml.Linq;

namespace LEGOINNOVATIVE.Pages.Orders
{
    public class OrderActiveModel : PageModel
    {
        private IOrderService _orderService;
        private ILoginService _loginService;
        private IPlanService _planService;

        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public string Title { get; set; }
        [BindProperty]
        public string Description { get; set; }
        [BindProperty]
        public string Name { get; set; }
        [BindProperty]
        public string Email { get; set; }
        [BindProperty]
        public string Phone { get; set; }
        [BindProperty]
        public string PlanType { get; set; }
        [BindProperty]
        public int Bricks { get; set; }
        [BindProperty]
        public bool Accepted { get; set; }

        public void OnGet(int id)
        {
            Order o = _orderService.FindOrder(id);
            Email = o.Email;
            Name = _loginService.FindProfile(Email).Name;
            Phone = _loginService.FindProfile(Email).Phone;
            Id = o.Id;
            Title = o.Title;
            Description = o.Description;
            PlanType = o.Plan;
            Bricks = _planService.FindPlan(PlanType).BrickAmount;
            Accepted = o.Accepted;
        }

        public IActionResult OnPostComplete(int id)
        {
            Order o = _orderService.FindOrder(id);
            o.Accepted = true;
            o.Completed = true;

            _orderService.EditOrder(o.Id, o);
            return RedirectToPage("/Sites/MasterProfile");
        }


        public OrderActiveModel(IOrderService orderService, ILoginService loginService, IPlanService planService)
        {
            _orderService = orderService;
            _loginService = loginService;
            _planService = planService;
        }



    }
}

LEGOINNOVATIVE/Pages/Orders/OrderDetails.cshtml.cs
using LEGOINNOVATIVE.Model;
using LEGOINNOVATIVE.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Numerics;
using System.Xml.Linq;

namespace LEGOINNOVATIVE.Pages.Orders
{
    public class OrderDetailsModel : PageModel
    {
        private IOrderService _orderService;
        private ILoginService _loginService;
        private IPlanService _planService;

        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public string Title { get; set; }
        [BindProperty]
        public string Description { get; set; }
        [BindProperty]
        public string Name { get; set; }
        [BindProperty]
        public string Email { get; set; }
        [BindProperty]
        public string Phone { get; set; }
        [BindProperty]
        public string PlanType { get; set; }
        [BindProperty]
        public int Bricks { get; set; }
        [BindProperty]
        public bool Accepted { get; set; }
        public void OnGet(int id)
        {
            Order o = _orderService.FindOrder(id);
            Email = o.Email;
            Name = _loginService.FindProfile(Email).Name;
            Phone = _loginService.FindProfile(Email).Phone;
            Id = o.Id;
            Title = o.Title;
            Description = o.Description;
            PlanType = o.Plan;
            Bricks = _planService.FindPlan(PlanType).BrickAmount;
            Accepted = o.Accepted;
        }
        public OrderDetailsModel(IOrderService orderService, ILoginService loginService, IPlanService planService)
        {
            _orderService = orderService;
            _loginService = loginService;
            _planService = planService;
        }
    }
}

LEGOINNOVATIVE/Pages/Orders/OrderEdit.cshtml.cs
using LEGOINNOVATIVE.MockData;
using LEGOINNOVATIVE.Model;
using LEGOINNOVATIVE.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LEGOINNOVATIVE.Pages.Orders
{
    public class OrderEditModel : PageModel
    {
        private IOrderService _orderService;
        private ILoginService _loginService;
        private MockPlans mockPlans = new MockPlans();
        public Order OrderRequest { get; set; }

        [BindProperty]
        public string Title { get; set; }
        [BindProperty]
        public string Description { get; set; }
        [BindProperty]
        public string PersonalMessage { get; set; }
        [BindProperty]
        public bool Publish { get; set; }

        [BindProperty]
        public int Id { get; set; }
        public List<string> Plans { get; set; }
        [BindProperty]
        public string ChosenPlan { get; set; }
        public void OnGet(int id)
        {
            Order o = _orderService.FindOrder(id);
            Id = o.Id;
            Title = o.Title;
            Description = o.Description;
            ChosenPlan = o.Plan;

            Plans = new List<string>();

            foreach (var pl in mockPlans.GetMockPlans())
            {
                Plans.Add(pl.Type);
            }
        }
    
        public IActionResult OnPostEdit()
        {

            Order newValues = new Order(Title, Description, PersonalMessage, Id, Publish, ChosenPlan, _loginService.Profiles.Email);

            _orderService.EditOrder(newValues.Id, newValues);
            return RedirectToPage("/Sites/MasterProfile");
        }

        public IActionResult OnPostCancel()
        {
            return RedirectToPage("/Sites/MasterProfile");
        }

        public OrderEditModel(IOrderService orderService, ILoginService loginService)
        {
            _orderService = orderService;
            _loginService = loginService;
        }

    }
}

LEGOINNOVATIVE/Pages/Orders/OrderRequests.cshtml.cs
using LEGOINNOVATIVE.MockData;
using LEGOINNOVATIVE.Model;
using LEGOINNOVATIVE.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Numerics;

namespace LEGOINNOVATIVE.Pages.Orders
{
    public class OrderRequestsModel : PageModel
    {
        private IOrderService _orderService;
        private ILoginService _loginService;
        private IPlanService _planService;

        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public string Title { get; set; }
        [BindProperty]
        public string Description { get; set; }
        [BindProperty]
        public string Name { get; set; }
        [BindProperty]
        public string Email { get; set; }
        [BindProperty]
        public string Phone { get; set; }
        [BindProperty]
        public string PlanType { get; set; }
        [BindProperty]
        public int Bricks { get; set; }
        [BindProperty]
        public bool Accepted { get; set; }

        public void OnGet(int id)
        {
            Order o = _orderService.FindOrder(id);
            Email = o.Email;
            Name = _loginService.FindProfile(Email).Name;
            Phone = _loginService.FindProfile(Email).Phone;
            Id = o.Id;
            Title = o.Title;
            Description = o.Description;
            PlanType = o.Plan;
            Bricks = _planService.FindPlan(PlanType).BrickAmount;
        }

        public OrderRequestsModel(IOrderService orderService, ILoginService loginService, IPlanService planService)
        {
            _orderService = orderService;
            _loginService = loginService;
            _planService = planService;
        }

        public IActionResult OnPostEdit()
        {
            return RedirectToPage("/Orders/OrderEdit");
        }

        public IActionResult OnPostDecline(int id)
        {
            _orderService.DeleteOrder(id);
            return RedirectToPage("/Sites/MasterProfile");
        }

        public IActionResult OnPostAccept(int id)
        {
            Order o = _orderService.FindOrder(id);
            o.Accepted = true;

            _orderService.EditOrder(o.Id, o);
            return RedirectToPage("/Sites/MasterProfile");
        }

    }
}

LEGOINNOVATIVE/Pages/Orders/MakeOrder.cshtml
@page
@model LEGOINNOVATIVE.Pages.Orders.MakeOrderModel
@{
}
<body class="makeOrderBody">
    <h1 class="makeOrderHeader">Make Order</h1>
    <div class="row">
        <div class="makeOrderDiv">
            <form method="post">
                <div class="form-group">
                    <p class="makeOrderText">Title</p>
                    <input asp-for="@Model.Title" class="makeOrderInput" placeholder="Descripe your idea" /><br />
                    <span asp-validation-for="@Model.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <p class="makeOrderText">Description</p>
                    <input asp-for="@Model.Description" class="makeOrderTextDescription" placeholder="Describe in detail" /><br />
                    <span asp-validation-for="@Model.Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <p class="makeOrderText">Your Personal Message</p>
                    <input asp-for="@Model.PersonalMessage" class="makeOrderInput" placeholder="Personal Message . . . " /><br />
                    <span asp-validation-for="@Model.PersonalMessage" class="text-danger"></span>
                </div>

                <p class="makeOrderText">Would you like to publish your IDEA to the LEGO IDEAS forum?</p>
                <input class="makeOrderCheckbox" type="checkbox" asp-for="@Model.Publish" /><p class="checkboxText">Yes</p>

                <p class="makeOrderText">Choose type</p>

                <select class="makeOrderDropdown" asp-for="ChosenPlan">
                    <a href="c:\users\theis\onedrive - zealand\swc\legoinnovative\legoinnovative\pages\orders\makeorder.cshtml.cs">c:\users\theis\onedrive - zealand\swc\legoinnovative\legoinnovative\pages\orders\makeorder.cshtml.cs</a>
                    <a href="c:\users\theis\onedrive - zealand\swc\legoinnovative\legoinnovative\pages\orders\makeorder.cshtml">c:\users\theis\onedrive - zealand\swc\legoinnovative\legoinnovative\pages\orders\makeorder.cshtml</a>
                    @foreach (var p in Model.Plans)
                    {
                        <option value="@p">@p</option>
                    }
                </select>

                <div class="form-group">
                    <input type="submit" value="Make Order" class="makeOrderButton" />
                </div>
            </form>
        </div>
    </div>
</body>

LEGOINNOVATIVE/Pages/Orders/OrderActive.cshtml
@page
@model LEGOINNOVATIVE.Pages.Orders.OrderActiveModel
@{
}
<body class="orderRequestBody">
    <div>
        <h1 class="orderRequestHeader">#@Model.Id. @Model.Title</h1>
    </div>
    <div class="displayFlex">
        <div class="orderRequestInfoDiv">
            <p class="orderRequestP">Description</p>
            <p class="orderRequestInfoContainer">@Model.Description</p>
        </div>
        <div class="orderRequestProfileInfoDiv">
            <p class="orderRequestP">Info</p>
            <ul class="orderRequestProfileInfoList">
                <li>Name: @Model.Name </li>
                <li>Email: @Model.Email</li>
                <li>Phone: @Model.Phone</li>
                <li>Plan: @Model.PlanType</li>
                <li>Bricks: Max @Model.Bricks</li>
                <li>Accepted: @Model.Accepted</li>
            </ul>
        </div>
    </div>
    <div class="buttonDiv">
        <form method="post">
            <div class="buttonContainer">
                <input type="submit" value="Complete" asp-page-handler="Complete" asp-route-id="@Model.Id" class="makeOrderButton" />
            </div>
        </form>
    </div>
</body>

LEGOINNOVATIVE/Pages/Orders/OrderDetails.cshtml
@page
@model LEGOINNOVATIVE.Pages.Orders.OrderDetailsModel
@{
}


<body class="orderRequestBody">
    <div class="arrowDiv">
        <a asp-page="/Sites/CustomerProfile" class="arrowButtonBack">&#60;</a>
    </div>
    <div>
        <h1 class="orderRequestHeader">#@Model.Id. @Model.Title</h1>
    </div>
    <div class="displayFlex">
        <div class="orderRequestInfoDiv">
            <p class="orderRequestP">Description</p>
            <p class="orderRequestInfoContainer">@Model.Description</p>
        </div>
        <div id="marginDivId" class="orderRequestProfileInfoDiv">
            <p class="orderRequestP">Info</p>
            <ul class="orderRequestProfileInfoList">
                <li>Name: @Model.Name </li>
                <li>Email: @Model.Email</li>
                <li>Phone: @Model.Phone</li>
                <li>Plan: @Model.PlanType</li>
                <li>Bricks: Max @Model.Bricks</li>
                <li>Accepted: @Model.Accepted</li>
            </ul>
        </div>
    </div>
</body>

LEGOINNOVATIVE/Pages/Orders/OrderEdit.cshtml
@page
@model LEGOINNOVATIVE.Pages.Orders.OrderEditModel
@{
}
<body class="makeOrderBody">
    <div class="orderEditContainer">
        <div>
            <form method="post">
                <div class="form-group">
                    <input type="hidden" asp-for="@Model.Id" class="makeOrderInput" /><br />
                </div>

                <div class="form-group">
                    <p class="makeOrderText">Title</p><br />
                    <input asp-for="@Model.Title" class="makeOrderInput" /><br />
                </div>

                <div class="form-group">
                    <p class="makeOrderText">Description</p><br />
                    <input asp-for="@Model.Description" class="makeOrderInput" /><br />
                </div>

                <div class="form-group">
                    <p class="makeOrderText">Publish</p><br />
                    <input type="checkbox" asp-for="@Model.Publish" class="makeOrderCheckbox" /><p class="checkboxText">Yes</p>
                    <br />
                </div>

                <div class="form-group">
                    <p class="makeOrderText">Plan</p><br />
                    <select class="makeOrderDropdown" asp-for="@Model.ChosenPlan">
                        @foreach (var p in Model.Plans)
                        {
                            <option value="@p">@p</option>
                        }
                    </select>
                </div>
                <div>
                    <div class="buttonContainer">
                        <input type="submit" value="Edit" asp-page-handler="Edit" asp-route-id="@Model.Id" class="makeOrderButton" />
                    </div>
                    <div class="buttonContainer">
                        <input type="submit" value="Cancel" asp-page-handler="Cancel" class="cancelButton" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>

LEGOINNOVATIVE/Pages/Orders/OrderRequests.cshtml
@page
@model LEGOINNOVATIVE.Pages.Orders.OrderRequestsModel
@{
}

<body class="orderRequestBody">
    <div class="arrowDiv">
        <a class="arrowButtonBack" asp-page="/Sites/MasterProfile">&#60;</a>
    </div>
    <div>
        <h1 class="orderRequestHeader">#@Model.Id. @Model.Title</h1>
    </div>
    <div>
        <div class="displayFlex">
            <div class="orderRequestInfoDiv">
                <p class="orderRequestP">Description</p>
                <p class="orderRequestInfoContainer">@Model.Description</p>
            </div>
            <div class="orderRequestProfileInfoDiv">
                <p class="orderRequestP">Info</p>
                <ul class="orderRequestProfileInfoList">
                    <li>Name: @Model.Name </li>
                    <li>Email: @Model.Email</li>
                    <li>Phone: @Model.Phone</li>
                    <li>Plan: @Model.PlanType</li>
                    <li>Bricks: Max @Model.Bricks</li>
                    <li>Accepted: @Model.Accepted</li>
                </ul>
            </div>
        </div>
        <div class="buttonDiv">
            <form method="post">
                <div class="buttonContainer">
                    <input type="submit" value="Accept" asp-page-handler="Accept" asp-route-id="@Model.Id" class="makeOrderButton" />
                </div>
                <div class="buttonContainer">
                    <a class="editOrderButton" asp-page="/Orders/OrderEdit" asp-route-id="@Model.Id">Edit</a>
                </div>
                <div class="buttonContainer">
                    <input type="submit" value="Decline" asp-page-handler="Decline" class="cancelButton" asp-route-id="@Model.Id"/>
                </div>
            </form>
        </div>
    </div>
</body>